#!/bin/bash

clipboard=$(xclip -out -selection clipboard | sed -e 's/file:\/\///')

if [[ -f $clipboard ]]; then
	xclip -sel clip -l 3 -t image/png $clipboard
	kdialog --icon $clipboard --title "Screenshot" --passivepopup "Screenshot copied to clipboard" 5
else
    echo "no such file"
fi
