#!/bin/bash

place=$(date +%m-%Y)
file=$(date +%d-%m-%Y_%H-%M-%S)


mkdir -p ~/Pictures/Screenshots/$place/

scrot ~/Pictures/tmp.png -z -q 75
display ~/Pictures/tmp.png &

sleep 1

window=$(xdotool search --onlyvisible --class 'display' | tail -n1)
xdotool windowfocus $window

gnome-screenshot -f ~/Pictures/Screenshots/$place/$file.png -p -a
sleep 1

if [[ -f ~/Pictures/Screenshots/$place/$file.png ]]; then
	xclip -sel clip -l 3 -t image/png ~/Pictures/Screenshots/$place/$file.png
	kdialog --icon ~/Pictures/Screenshots/$place/$file.png --title "Screenshot" --passivepopup "Screenshot copied to clipboard" 5 &
fi

xdotool windowkill $window
